### PR TITLE
Joshua's greeting.

### PR DESCRIPTION
**Pull request by Jeklund99**
This adds Joshua's greeting.

### CODE REVIEW

**Review by DanteMillerDS — DISMISSED** [review]

**Review by RichardLussier — DISMISSED** [review]
Looks good!

**Review by RichardLussier — DISMISSED** [review]
Looks good

**Review by NicMcPhee — DISMISSED** [review]
Looks great – thanks!

**Review by RichardLussier — APPROVED** [review]
Looks good

**Review by day00090 — APPROVED** [review]
Everything appears to be order.

**Pull request merged**
